/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package descubrasenha;

import java.util.Random;

/**
 *
 * @author dario
 */
public class Senha extends javax.swing.JFrame {

    /**
     * Creates new form Senha
     */
    int senha1;
    int senha2;
    int senha3;
    int senha4;
    int Co = 0;
    int tentativa[][] = new int[9][4];
    int resultado[][] = new int[9][2];
    int senha[] = new int[4];
    public Senha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSenha = new javax.swing.JToggleButton();
        n1 = new javax.swing.JSpinner();
        n2 = new javax.swing.JSpinner();
        n3 = new javax.swing.JSpinner();
        n4 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        lblTentativa0 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c0 = new javax.swing.JLabel();
        e0 = new javax.swing.JLabel();
        lblTentativa1 = new javax.swing.JLabel();
        lblTentativa2 = new javax.swing.JLabel();
        lblTentativa3 = new javax.swing.JLabel();
        lblTentativa4 = new javax.swing.JLabel();
        lblTentativa5 = new javax.swing.JLabel();
        lblTentativa6 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        btnGeraSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSenha.setText("Senha?");
        btnSenha.setEnabled(false);
        btnSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaActionPerformed(evt);
            }
        });

        n1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        n1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));

        n2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        n2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));

        n3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        n3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));

        n4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        n4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));

        lblTentativa0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa0.setText("(X) (X) (X) (X)");

        jLabel3.setText("Certos");

        jLabel4.setText("Errados");

        c0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c0.setForeground(new java.awt.Color(0, 51, 255));
        c0.setText("0");

        e0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e0.setForeground(new java.awt.Color(255, 51, 51));
        e0.setText("0");

        lblTentativa1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa1.setText("(X) (X) (X) (X)");

        lblTentativa2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa2.setText("(X) (X) (X) (X)");

        lblTentativa3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa3.setText("(X) (X) (X) (X)");

        lblTentativa4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa4.setText("(X) (X) (X) (X)");

        lblTentativa5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa5.setText("(X) (X) (X) (X)");

        lblTentativa6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTentativa6.setText("(X) (X) (X) (X)");

        e1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e1.setForeground(new java.awt.Color(255, 51, 51));
        e1.setText("0");

        c1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c1.setForeground(new java.awt.Color(0, 51, 255));
        c1.setText("0");

        e2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e2.setForeground(new java.awt.Color(255, 51, 51));
        e2.setText("0");

        c2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c2.setForeground(new java.awt.Color(0, 51, 255));
        c2.setText("0");

        e3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e3.setForeground(new java.awt.Color(255, 51, 51));
        e3.setText("0");

        c3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c3.setForeground(new java.awt.Color(0, 51, 255));
        c3.setText("0");

        e4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e4.setForeground(new java.awt.Color(255, 51, 51));
        e4.setText("0");

        c4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c4.setForeground(new java.awt.Color(0, 51, 255));
        c4.setText("0");

        e5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e5.setForeground(new java.awt.Color(255, 51, 51));
        e5.setText("0");

        c5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c5.setForeground(new java.awt.Color(0, 51, 255));
        c5.setText("0");

        e6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        e6.setForeground(new java.awt.Color(255, 51, 51));
        e6.setText("0");

        c6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        c6.setForeground(new java.awt.Color(0, 51, 255));
        c6.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(c0)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTentativa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(e0))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(e2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(e1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa0)
                    .addComponent(c0)
                    .addComponent(e0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa1)
                    .addComponent(e1)
                    .addComponent(c1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa2)
                    .addComponent(e2)
                    .addComponent(c2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa3)
                    .addComponent(e3)
                    .addComponent(c3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa4)
                    .addComponent(e4)
                    .addComponent(c4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa5)
                    .addComponent(e5)
                    .addComponent(c5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTentativa6)
                    .addComponent(e6)
                    .addComponent(c6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\ICONS\\8271_64x64.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\ICONS\\6244_32x32.png")); // NOI18N

        lblMensagem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(0, 204, 0));
        lblMensagem.setText("...");

        btnGeraSenha.setText("Gerar Senha");
        btnGeraSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGeraSenha))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSenha)
                        .addGap(15, 15, 15))
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(lblMensagem))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeraSenha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaActionPerformed

        // TODO add your handling code here:

        int certo=0;
        int errado=0;
        tentativa[Co][0]= Integer.parseInt(n1.getValue().toString());
        tentativa[Co][1]= Integer.parseInt(n2.getValue().toString());
        tentativa[Co][2]= Integer.parseInt(n3.getValue().toString());
        tentativa[Co][3]= Integer.parseInt(n4.getValue().toString());
        
        for (int n=0;n<4;n++){
            for(int nn=0;nn<4;nn++ ){
                if(tentativa[Co][n] == senha[nn]){
                    if(n==nn){
                        certo++;
                    }else{
                        errado++;
                    }
                }
            }
            
        }
        resultado[Co][0]=certo;
        resultado[Co][1]=errado;
        
        c0.setText(Integer.toString(resultado[0][0]));
        e0.setText(Integer.toString(resultado[0][1]));
        lblTentativa0.setText(Integer.toString(tentativa[0][0]) + "-" +
                Integer.toString(tentativa[0][1]) + "-" +
                Integer.toString(tentativa[0][2]) + "-" +
                Integer.toString(tentativa[0][3])
                );
        
        c1.setText(Integer.toString(resultado[1][0]));
        e1.setText(Integer.toString(resultado[1][1]));
        lblTentativa1.setText(Integer.toString(tentativa[1][0]) + "-" +
                Integer.toString(tentativa[1][1]) + "-" +
                Integer.toString(tentativa[1][2]) + "-" +
                Integer.toString(tentativa[1][3])
                );
        
        c2.setText(Integer.toString(resultado[2][0]));
        e2.setText(Integer.toString(resultado[2][1]));
        lblTentativa2.setText(Integer.toString(tentativa[2][0]) + "-" +
                Integer.toString(tentativa[2][1]) + "-" +
                Integer.toString(tentativa[2][2]) + "-" +
                Integer.toString(tentativa[2][3])
                );
        
        c3.setText(Integer.toString(resultado[3][0]));
        e3.setText(Integer.toString(resultado[3][1]));
        lblTentativa3.setText(Integer.toString(tentativa[3][0]) + "-" +
                Integer.toString(tentativa[3][1]) + "-" +
                Integer.toString(tentativa[3][2]) + "-" +
                Integer.toString(tentativa[3][3])
                ); 
        
        c4.setText(Integer.toString(resultado[4][0]));
        e4.setText(Integer.toString(resultado[4][1]));
        lblTentativa4.setText(Integer.toString(tentativa[4][0]) + "-" +
                Integer.toString(tentativa[4][1]) + "-" +
                Integer.toString(tentativa[4][2]) + "-" +
                Integer.toString(tentativa[4][3])
                );
        
        c5.setText(Integer.toString(resultado[5][0]));
        e5.setText(Integer.toString(resultado[5][1]));
        lblTentativa5.setText(Integer.toString(tentativa[5][0]) + "-" +
                Integer.toString(tentativa[5][1]) + "-" +
                Integer.toString(tentativa[5][2]) + "-" +
                Integer.toString(tentativa[5][3])
                );
        
        c6.setText(Integer.toString(resultado[6][0]));
        e6.setText(Integer.toString(resultado[6][1]));
        lblTentativa6.setText(Integer.toString(tentativa[6][0]) + "-" +
                Integer.toString(tentativa[6][1]) + "-" +
                Integer.toString(tentativa[6][2]) + "-" +
                Integer.toString(tentativa[6][3])
                );
        
        if(certo==4)
        {
            lblMensagem.setText("Acertou, a senha é " + senha[0] + "-" + senha[1] + "-" + senha[2] + "-" + senha[3]);
            btnSenha.setEnabled(false);
            btnGeraSenha.setEnabled(true);
            return;
        }
        Co++;
        if(Co==7)
        {
            lblMensagem.setText("Falhou, a senha é " + senha[0] + "-" + senha[1] + "-" + senha[2] + "-" + senha[3]);
            btnSenha.setEnabled(false);
            btnGeraSenha.setEnabled(true);
            return;
        }
    }//GEN-LAST:event_btnSenhaActionPerformed
    static int geranumero(){
            Random n = new Random();
            int x = n.nextInt(10);
            return x;
    }
    private void LimpaTela(){
        lblMensagem.setText("Começou...");
        lblTentativa0.setText("(X)(X)(X)(X)");
        lblTentativa1.setText("(X)(X)(X)(X)");
        lblTentativa2.setText("(X)(X)(X)(X)");
        lblTentativa3.setText("(X)(X)(X)(X)");
        lblTentativa4.setText("(X)(X)(X)(X)");
        lblTentativa5.setText("(X)(X)(X)(X)");
        lblTentativa6.setText("(X)(X)(X)(X)");
        e0.setText("0");
        e1.setText("0");
        e2.setText("0");
        e3.setText("0");
        e4.setText("0");
        e5.setText("0");
        e6.setText("0");
        c0.setText("0");
        c1.setText("0");
        c2.setText("0");
        c3.setText("0");
        c4.setText("0");
        c5.setText("0");
        c6.setText("0");
        for(int tt=0;tt<7;tt++){
            
                tentativa[tt][0]=0;
                tentativa[tt][1]=0;
                tentativa[tt][2]=0;
                tentativa[tt][3]=0;
                tentativa[tt][4]=0;
                tentativa[tt][5]=0;
                tentativa[tt][6]=0;
                resultado[tt][1]=0;
                resultado[tt][3]=0;

        }
    }
    private void btnGeraSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraSenhaActionPerformed
        // TODO add your handling code here:
        
        lblMensagem.setText("...");
        Co=0;
        senha[0]=geranumero();
        senha[1]=geranumero();
        senha[2]=geranumero();
        senha[3]=geranumero();
        while(senha[0] == senha[1]){
            senha[0] = geranumero();
            senha[1] = geranumero();
        }
        while(senha[2] ==senha[0] || senha[2] ==senha[1]){
            senha[2] = geranumero();
        }
        while (senha[3] == senha[2] || senha[3] == senha[1] || senha[3] == senha[0]){
            senha[3] = geranumero();
        }
        btnSenha.setEnabled(true);
        btnGeraSenha.setEnabled(false);
        LimpaTela();
        //lblMensagem.setText( "A senha eh " + Integer.toString(senha[0]) + ":" + Integer.toString(senha[1]) + 
         //       ":" + Integer.toString(senha[2])+ ":" + Integer.toString(senha[3]));
         //   lblMensagem.setText(Integer.toString(x));
            
    }//GEN-LAST:event_btnGeraSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Senha().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeraSenha;
    private javax.swing.JToggleButton btnSenha;
    private javax.swing.JLabel c0;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel e0;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTentativa0;
    private javax.swing.JLabel lblTentativa1;
    private javax.swing.JLabel lblTentativa2;
    private javax.swing.JLabel lblTentativa3;
    private javax.swing.JLabel lblTentativa4;
    private javax.swing.JLabel lblTentativa5;
    private javax.swing.JLabel lblTentativa6;
    private javax.swing.JSpinner n1;
    private javax.swing.JSpinner n2;
    private javax.swing.JSpinner n3;
    private javax.swing.JSpinner n4;
    // End of variables declaration//GEN-END:variables
}
